[[http_requests]]
== HTTP Requests

=== Must: Use HTTP Methods Correctly

Prefer the usage of the common methods [underline]#**GET, POST, DELETE, PUT**#.

Be compliant with the standardized HTTP method semantics summarized as follows:

==== GET

GET requests are used to read a single resource or query set of resources.

* GET requests for individual resources will usually generate a 404 if the resource does not exist

* GET requests for collection resources may return either 200 (if the listing is empty) or 404 (if the list is missing)

* GET requests must NOT have request body payload

**Note:** GET requests on collection resources should provide a sufficient
filter mechanism as well as <<Pagination>>.

==== "GET with Body"

APIs sometimes face the problem, that they have to provide extensive structured request information with GET, 
that may even conflicts with the size limits of clients, load-balancers, and servers. 
As we require APIs to be standard conform (body in GET must be ignored on server side), 
API designers have to check the following two options:

1. GET with URL encoded query parameters: 
when it is possible to encode the request information in query parameters, 
respecting the usual size limits of clients, gateways, and servers, this should be the first choice. 
The request information can either be provided distributed 
to multiple query parameters or a single structured URL encoded string.

2. POST with body content: when a GET with URL encoded query parameters is not possible, 
a POST with body content must be used. 
In this case the endpoint must be documented with the hint `GET with a body` to transport the GET semantic of this call.

NOTE: If the query paramters exceed the size limits, reconsider your API design before use of POST with body content.

==== PUT

PUT requests are used to create or update **entire** resources - single or collection resources. 
The semantic is best described as »__please put the enclosed representation at the resource mentioned by the URL, replacing
any existing resource.__«.

* PUT requests are usually applied to single resources, and not to
collection resources, as this would imply replacing the entire
collection

* PUT requests are usually robust against non-existence of resources by implicitly creating before updating

* on successful PUT requests, the server will **replace the entire resource** addressed by the URL with the representation passed in the payload (subsequent reads will deliver the same payload)

* successful PUT requests will usually generate 200 or 204 (if the resource was updated - with or without actual content returned), and 201 (if the resource was created)

To prevent unnoticed concurrent updates when using PUT, the combination of `<<ETag, ETag>>` and `If-(None-)Match` 
headers should be considered to signal the server stricter demands to expose conflicts and prevent lost updates.

==== POST

POST requests are idiomatically used to create single resources on a collection resource endpoint,
but other semantics on single resources endpoint are equally possible.
The semantic for collection endpoints is best described as
»__please add the enclosed representation to the collection resource identified by the URL__«.
The semantic for single resource endpoints is best described as
»__please execute the given well specified request on the collection resource identified by the URL__«.

* POST request should only be applied to collection resources, 
and normally not on single resource, as this has an undefined semantic

* on successful POST requests, the server will create one or multiple new resources and provide their URI/URLs in the response

* successful POST requests will usually generate 200 (if resources have been updated),
201 (if resources have been created), and 202 (if the request was accepted but has not been finished yet)


NOTE: Resource IDs with respect to POST requests are created and maintained by server and returned with response payload.
Posting the same resource twice is by itself **not** required to be idempotent and may result in multiple resource instances.
Anyhow, if external URIs are present that can be used to identify duplicate requests,
it is best practice to implement POST in an idempotent way.

PATCH request are only used for partial update of single resources,
i.e. where only a specific subset of resource fields should be replaced.
The semantic is best described as
»__please change the resource identified by the URL according to my change request__«.
The semantic of the change request is not defined in the HTTP standard 
and must be described in the API specification by using suitable media 
types.

==== PATCH

PATCH request are only used for partial update of single resources,
i.e. where only a specific subset of resource fields should be replaced.
The semantic is best described as »__please change the resource identified by the URL according to my change request__«.
The semantic of the change request is not defined in the HTTP standard 
and must be described in the API specification by using suitable media types.

* PATCH requests are usually applied to single resources,
and not on collection resources, as this would imply patching on the entire collection

* PATCH requests are usually not robust against non-existence of resource instances

* on successful PATCH requests, the server will update parts of the
resource addressed by the URL as defined by the change request in thepayload

* successful PATCH requests will usually generate 200 or 204 (if resources have been updated)

* with or without updated content returned

==== 
NOTE: Since implementing PATCH correctly is a bit tricky, we strongly
suggest to choose one and only one of the following patterns per endpoint, in preference order:

1.  use PUT with complete objects to update a resource as long as
feasible (i.e. do not use PATCH at all).

2.  use PATCH with partial objects to only update parts of a resource, whenever possible. 

3.  use PATCH with a specialized media type `application/json-patch+json` that includes instructions on how to change the resource.

4.  use POST (with a proper description of what is happening) instead of PATCH 
if the request does not modify the resource in a way defined by the semantics of the media type.
====

==== DELETE

DELETE request are used to delete resources. 
The semantic is best described as »__please delete the resource identified by the URL__«.

* DELETE requests are usually applied to single resources, not on collection resources, as this would imply deleting the entire collection

* successful DELETE request will usually generate 200 (if the deleted resource is returned) or 204 (if no content is returned)

* failed DELETE request will usually generate 404 (if the resource cannot be found) or 410 (if the resource was already deleted before)

==== HEAD

HEAD requests are used to retrieve the header information of single
resources and resource collections.

* HEAD has exactly the same semantics as GET, but returns headers only, no body.

==== OPTIONS

OPTIONS are used to inspect the available operations (HTTP methods) of a given endpoint.

* OPTIONS requests usually either return a comma separated list of methods (provided by an ``Allow:``-Header) 
or as a structured list of link templates

NOTE: OPTIONS is rarely implemented, though it could be used to self-describe the full functionality of a resource.

=== Must: Fulfill Safeness and Idempotency Propeties

An operation can be…

* idempotent, i.e. operation will have the same effect on the server’s state if executed once or multiple times 
(note: this does not necessarily mean returning the same response or status code)

* safe, i.e. must not have side effects such as state changes

|====
| HTTP method | safe | idempotent
| GET | Yes | Yes
| PUT | No | Yes
| POST | No | No
| DELETE | No | Yes
| PATCH | No | No
| OPTIONS | Yes | Yes
| HEAD | Yes | Yes
|====