[[json_naming]]
== JSON Naming

These guidelines provide recommendations for defining JSON data.
JSON here refers to the “application/json” media type and custom JSON media types defined for APIs.

=== Must: Property names must be ASCII camelCase `^[a-z_][a-z0-9]*$`

Property names are restricted to ASCII strings.
The first character must be a letter, or an underscore, and subsequent characters can be a letter or a number.

NOTE: It is recommended to use _ at the start of property names only for keywords like _links or _embedded.

Rationale: No established industry standard exists.
It’s essential to establish a consistent look and feel such that JSON looks as if it came from the same hand.

=== Must: Array names should be pluralized

To indicate they contain multiple values prefer to pluralize array names. 
This implies that object names should in turn be singular.

=== Must: Boolean property values must not be null

Schema based JSON properties that are by design booleans must not be presented as nulls. 
A boolean is essentially a closed enumeration of two values, true and false. 
If the content has a meaningful null value, strongly prefer to replace the boolean 
with enumeration of named values or statuses - for example accepted_terms_and_conditions 
with true or false can be replaced with terms_and_conditions with values yes, no and unknown.

=== Must: Empty array should not be null

Empty array values can unambiguously be represented as the empty list, `[]`.


=== Must: Serialization of default values

Functional properties should always be serialized irrespective of the fact that the value is default.

Modern JSON Serializers allows to skip the serialization of default values.

[source,java]
----
public class Foo {
  private int id = 4;
  private int counter = 0;
  private boolean active = true;
  private boolean broken = false;
}
----

If default values are not serialized, the json representation includes only the fields with non-default values.

[source,JavaScript]
----
{
    "id": 4,
    "active": "true"
}
----

Configure your Serializer to include default values:
    
[source,JavaScript]
----
{
    "id": 4,
    "counter": 0
    "active": "true"
    "broken": "false"
}
----


NOTE: Technical values having default properties may be omitted.

[source,JavaScript]
----
{
  "id": "bfd15e9a-5f06-46c0-b1e9-e8dc9658c09e",
  "dispatchDateTime": "2018-06-05T13:27:20.4716347Z",
  "outboundOrderId": "1f00e698-497a-44b5-8786-8c1398791871",


  //Functional values should always be serialized.
  //fulfilled (just an arbitrary example property) is a prpoerty which is "functional" as it represents a functional meaning.
  //It has a default value of "false" but it should still be present (serialized) in the json.
  "fulfilled": "false",


  "_links": {
    //_links is part of HATEOAS Hal specs. This property and all its content is technical (not functional).
    // so if there are technical properties having default value, these may be ommitted.

    //For e.g. "templated" property of HAL may be ommitted if it is false.
    //See http://stateless.co/hal_specification.html for curies and template
    "self": {
      "href": "https://dummyrootaddress/consignments/bfd15e9a-5f06-46c0-b1e9-e8dc9658c09e"
    },
    "packages": {
      "href": "https://dummyrootaddress/consignments/bfd15e9a-5f06-46c0-b1e9-e8dc9658c09e/packages"
    }
  }
}
----

=== Must: Enumerations should be represented as Strings

Strings are a reasonable target for values that are by design enumerations.

[[date_format]]
=== Must: Date property value

Use the date and time format according https://en.wikipedia.org/wiki/ISO_8601[ISO 8601].

* for "date" use strings matching `date-fullyear "-" date-month "-" date-mday`, for example: `2015-05-28`

* for "date-time" use strings matching `full-date "T" full-time`, for example `2015-05-28T14:07:17Z`

NOTE: Date should be always in UTC. 
Localization of dates should be done by the services that provide user interfaces, if required.

